### ISSUE TITLE
PNG logos disguised as vector logos

### ISSUE THREAD

**Issue by amenk** [Chapa-Et/ethiopianlogos#11]
> This is an open source project for downloading free, high quality vector logos of Ethiopian companies.

For example the CBE logo is actually a PNG logo in the SVG:

https://github.com/Chapa-Et/ethiopianlogos/blame/main/logos/commercial_bank_of_ethiopia/commercial_bank_of_ethiopia.svg

Should we maybe delete such SVGs and fall back to the PNG instead until a vector logo is available?

Actually it's the case for most of the logos here.

The only actual vector logos I found are:

* bandira_addis_map_entertainment/bandira_addis_map_entertainment.svg
* chapa/chapa.svg
* dangote/dangote.svg
* zemen_bank/zemen_bank.svg

The problem is, that when reusing the logos, it's not clear which one is the primary / higher quality.

Another solution would be to put a hint in the `logos.json` to specify which one is the primary version and which one is the converted one.

**Comment by isrugeek** [comment]
We were hoping the companies could fix their logos. But putting a hint in the `logos.json` makes sense, either.
